default: &default
  adapter: mysql2
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: db/deploy_rails_capistrano_development

test:
  <<: *default
  database: db/deploy_rails_capistrano_test

production:
  <<: *default
  database: deploy_rails_capistrano_production
  username: deploy_rails_capistrano
  password: <%= ENV['DATABASE_PASSWORD'] %>
